// Copyright (c) 2026 RiftShard-forge. All Rights Reserved.
// Unauthorized copying, distribution, or use is strictly prohibited.

// exportExcel.js
// Dynamic xlsx export — tabs generated from audit categories

import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';

/**
 * Converts an array of objects to a worksheet.
 * Filters out internal _ prefixed columns from display.
 */
function toWorksheet(rows, includeAuditColumns = true) {
  if (!rows || rows.length === 0) {
    return XLSX.utils.aoa_to_sheet([['No data found for this category.']]);
  }

  const allKeys = Object.keys(rows[0]).filter(k => {
    if (k.startsWith('_') && !includeAuditColumns) return false;
    return true;
  });

  const displayKeys = allKeys.filter(k => !k.startsWith('_'));
  const auditKeys = allKeys.filter(k => k.startsWith('_'));
  const orderedKeys = [...displayKeys, ...auditKeys.map(k => k.replace('_', ''))];
  const sourceKeys = [...displayKeys, ...auditKeys];

  const data = [
    orderedKeys,
    ...rows.map(row => sourceKeys.map(key => {
      const val = row[key];
      if (val === null || val === undefined) return '';
      if (typeof val === 'object') return JSON.stringify(val);
      return val.toString();
    }))
  ];

  const ws = XLSX.utils.aoa_to_sheet(data);
  ws['!cols'] = orderedKeys.map(key => ({ wch: Math.max(key.length, 15) }));
  return ws;
}

/**
 * Creates a summary worksheet.
 */
function toSummarySheet(assetName, summary, timestamp) {
  const sanitize = v => {
    if (v === null || v === undefined) return '';
    if (typeof v === 'object') return JSON.stringify(v);
    return v.toString();
  };

  const data = [
    ['Audit Summary'],
    [''],
    ['Audit Profile', sanitize(assetName)],
    ['Run Date', sanitize(timestamp)],
    [''],
    ['Category', 'Count'],
    ...Object.entries(summary.byCategory).map(([cat, count]) => [cat, count]),
    [''],
    ['Suppressed', summary.totalBlacklisted],
    ['Under Investigation', summary.totalUnderInvestigation || 0],
    ['Delta Flag Changes', summary.totalDelta || 0],
    ['Clean', summary.totalClean],
    [''],
    ['Total Processed', summary.totalProcessed],
    ['Total Flagged', summary.totalFlagged],
    [''],
    [''],
    ['Generated by', 'Inventory Audit Tool'],
    ['Author', 'RiftShard-forge'],
    ['License', 'Copyright (c) 2026 RiftShard-forge. All Rights Reserved.'],
    ['', 'Unauthorized copying or distribution is strictly prohibited.']
  ];

  const ws = XLSX.utils.aoa_to_sheet(data);
  ws['!cols'] = [{ wch: 30 }, { wch: 15 }];
  return ws;
}

/**
 * MAIN EXPORT FUNCTION
 * Generates .xlsx with dynamic tabs based on audit categories.
 * Tabs are ordered by rule severity (lowest number = leftmost tab).
 */
export function exportToExcel(assetName, results) {
  const timestamp = results.runDate || new Date().toLocaleString();
  const dateStamp = new Date().toISOString().split('T')[0];
  const fileName = `${assetName}_Audit_${dateStamp}.xlsx`;

  const wb = XLSX.utils.book_new();

  // Tab 1: Summary
  XLSX.utils.book_append_sheet(
    wb,
    toSummarySheet(assetName, results.summary, timestamp),
    'Summary'
  );

  // Dynamic category tabs — sorted by severity (lowest = leftmost)
  const sortedCategories = Object.entries(results.byCategory).sort((a, b) => {
    const severityA = results.categorySeverity?.[a[0]] ?? 99;
    const severityB = results.categorySeverity?.[b[0]] ?? 99;
    return severityA - severityB;
  });

  sortedCategories.forEach(([category, rows]) => {
    const safeName = category.substring(0, 31).replace(/[:\\/?*[\]]/g, '-');
    XLSX.utils.book_append_sheet(wb, toWorksheet(rows), safeName);
  });

  // Suppressed tab
  if (results.blacklisted && results.blacklisted.length > 0) {
    XLSX.utils.book_append_sheet(
      wb,
      toWorksheet(results.blacklisted),
      'Suppressed'
    );
  }

  // Under Investigation tab
  if (results.underInvestigation && results.underInvestigation.length > 0) {
    XLSX.utils.book_append_sheet(
      wb,
      toWorksheet(results.underInvestigation),
      '🔍 Under Investigation'
    );
  }

  // Delta Flag Changes tab — only added if delta detection found changes
  if (results.deltaAssets && results.deltaAssets.length > 0) {
    XLSX.utils.book_append_sheet(
      wb,
      toWorksheet(results.deltaAssets),
      'Delta Flag Changes'
    );
  }

  // Clean tab
  XLSX.utils.book_append_sheet(
    wb,
    toWorksheet(results.clean, false),
    'Clean'
  );

  // Unaccounted tab — only added if Safety Net found dropped assets
  if (results.unaccounted && results.unaccounted.length > 0) {
    XLSX.utils.book_append_sheet(
      wb,
      toWorksheet(results.unaccounted, false),
      '⚠ Unaccounted'
    );
  }

  const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  const blob = new Blob([excelBuffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  });
  saveAs(blob, fileName);
}